zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    projects-service: /projects/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

spring:
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
