iterations:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  profiles: default
eureka:
  instance:
    hostname: iterations-service

---
spring:
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
